Pivot sim
AEMBOT/FRC_2024 pull request #13
Opened 2024-01-27 21:43 UTC by WiseHunter42

Added PivotIOSim

2024-01-28 05:15 UTC, ItsDaWither requested changes
solid implementation, see minor changes

2024-01-28 05:15 UTC, witherrrr commented on src/main/java/frc/robot/Constants.java
> +  }
ff kv and exponential kv are the exact same thing, the exponential profile uses the system constants to characterize the system.
addtl for this codebase pls keep the constants in the IO implementation itself because constants vary between impls and its easier to keep things clean if the constants for each impl are in the impl itself

2024-01-28 05:15 UTC, ItsDaWither commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +    io.resetExp(Constants.PivotSimConstants.exponentialKV, Constants.PivotSimConstants.exponentialKA); // Currently Set up to run Sim, needs a switch statement
exp profile kv ka is impl specific because same thing i commented on constants, you can get rid of resetExp entirely

2024-01-28 05:15 UTC, ItsDaWither commented on src/main/java/frc/robot/subsystems/pivot/Pivot.java
> +    pivotSetpoint = positionRad;
pivotsetpoint is doing nothing of use, just call io.setPosition in runPosition

2024-01-28 05:15 UTC, ItsDaWither commented on src/main/java/frc/robot/subsystems/pivot/PivotIOSim.java
> +    sim.update(0.2);
dtseconds is 0.02

2024-01-28 05:15 UTC, ItsDaWither commented on src/main/java/frc/robot/subsystems/pivot/PivotIOSim.java
> +    inputs.pivotCurrentAmps = new double[]{sim.getCurrentDrawAmps(), sim.getCurrentDrawAmps()};
why duplicate, just use one value lol

2024-01-28 05:15 UTC, ItsDaWither commented on src/main/java/frc/robot/subsystems/pivot/PivotIOSim.java
> +    setVoltage(0.0);
do you need openloop = false here

2024-01-29 01:55 UTC, ItsDaWither commented on src/main/java/frc/robot/subsystems/pivot/PivotIOSim.java
> +  private DCMotorSim sim = new DCMotorSim(DCMotor.getNEO(2), 1, 1); // Numbers TODO
this should be a single jointed arm sim with gear ratio 300:1

2024-01-29 02:34 UTC, ItsDaWither approved these changes
I fixed all of the issues

2024-01-29 02:43 UTC, merged